#!/usr/bin/env bash

shopt -s extglob

# Check if running as root
[ "$EUID" -ne 0 ] && echo "Please run as root." && exit 1

# Backup old configuration
mkdir -p /etc/nixos/old
dir=$(date +"%Y_%m_%d_%H%M%S")
mkdir -p /etc/nixos/old/"${dir}"
mv -f /etc/nixos/!(old) /etc/nixos/old/"${dir}"

# Copy configuration files
cp -rf nixos/* /etc/nixos/
